# vault_secrets.yml - Ansible Vault Encrypted Secrets Template
# Author: AbayK
# Description: Template for storing encrypted secrets
#
# To encrypt this file:
#   ansible-vault encrypt vault_secrets.yml
#
# To edit encrypted file:
#   ansible-vault edit vault_secrets.yml
#
# To decrypt file:
#   ansible-vault decrypt vault_secrets.yml
#
# To run playbook with vault:
#   ansible-playbook playbook_AbayK.yml --ask-vault-pass

---
# Database credentials
vault_db_password: "todopass"
vault_db_root_password: "rootpass"

# Docker registry credentials
vault_docker_username: "abayk"
vault_docker_password: "your_docker_password"

# Git credentials
vault_git_token: "your_git_token"

# Jenkins admin password
vault_jenkins_admin_password: "admin_password"
